// flow-typed signature: 5feaa07dae2f3ebe5fc0b72edbc31e29
// flow-typed version: <<STUB>>/src_v^1.1.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'src'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'src' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'src/test/src-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'src/index' {
  declare module.exports: $Exports<'src'>;
}
declare module 'src/index.js' {
  declare module.exports: $Exports<'src'>;
}
declare module 'src/test/src-test.js' {
  declare module.exports: $Exports<'src/test/src-test'>;
}
