// @flow strict
import React from 'react';
import styled from 'styled-components';
import { Query } from 'react-apollo';

import GET_THINGS from './thing.query';

const Container = styled.div`
  display: flex;
  flex-direction: column;
  padding-top: 10px;
`;

const Item = styled.div`
  font-size: 16px;
`;

// TODO: add proper autogenerated type def
type ThingsQueryType = any;

const ThingListExample = () => (
  <Query query={GET_THINGS}>
    {({ loading, error, data }: ThingsQueryType) => {
      if (loading) return 'Loading...';
      if (error) return `Error! ${error.message}`;

      return (
        <Container>
          {data.allThings.map(thing => (
            <Item key={thing.id}>{thing.name}</Item>
          ))}
        </Container>
      );
    }}
  </Query>
);

export default ThingListExample;
